# Generated by Django 3.1.7 on 2021-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
