# Generated by Django 3.1.7 on 2021-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210405_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_hr_conversation',
            field=models.BooleanField(default=False),
        ),
    ]
