# Generated by Django 3.1.7 on 2021-04-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210405_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_for_accesses',
            field=models.BooleanField(default=False),
        ),
    ]
